xle_cafe:
    resource: "@XleCafeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Resources/config/routing.yml'
    prefix:   /app

home:
    path:     /
    defaults: { _controller: "XleCafeBundle:Cafe:list" }
    methods:  [GET, POST]
