security_login:
    path:     /login
    defaults: { _controller: "AppBundle:Security:login" }
    methods:  [GET, POST]

security_logout:
    path:     /logout
    defaults: { _controller: "AppBundle:Security:logout" }
    methods:  [GET, POST]


