<?php

namespace Xle\CafeBundle\Repository;

/**
 * CafeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CafeRepository extends \Doctrine\ORM\EntityRepository {

    public function findByGmKeyInArray($gmIdsArray): array {
        $qb = $this->createQueryBuilder('c')
            ->andWhere('c.googlePlaceId IN (:gmIdsArray)')
            ->setParameter('gmIdsArray', $gmIdsArray)
            ->groupBy('c.googlePlaceId')
            ->getQuery();
      //  $sql = $qb->getSQL();
        return $qb->execute();
    }

    public function findByGmKeyInArray2($mapCafesIds) {
        $mapCafesIdsStr = implode(',', $mapCafesIds);
        $query = $this->getEntityManager()
            ->createQuery(
                "SELECT c FROM XleCafeBundle:Cafe c WHERE c.googlePlaceId IN ($mapCafesIdsStr)"
            );
    //    $sql = $query->getSQL();
        return $query->getResult();
    }


}
